version: '3.8'

services:
  api:
    build: ./
    command: >
      sh -c "python manage.py flush --no-input &&
           python manage.py migrate &&
           python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
      - static:/src/app/static
      - static:/src/app/media

    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  
  db:
    image: postgres:12.0-alpine
    env_file: ./.env.postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # nginx:
  #   build: ./nginx
  #   container_name: dev-nginx
  #   ports:
  #     - 8080:80
  #   restart: always
  #   volumes:
  #     - static:/src/app/static
  #     - media:/src/app/media
  #   depends_on:
  #     - api
  #     - react
  #     - db

volumes:
  postgres_data:
  static:
  media:
